=== ligoj/cli/ligojcli/plugins/schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "Configuration",
    "$defs": {
        "permissions": {
            "type": "array",
            "maxItems": 1,
            "items": {
                "type": "string",
                "pattern": "[-A-Za-z0-9]+"
            }
        },
        "roles_simple": {
            "type": "object",
            "minProperties": 1,
            "propertyNames": {
                "pattern": "^[-A-Za-z0-9]+$"
            },
            "patternProperties": {
                "^.*$": {
                    "type": "object",
                    "propertyNames": {
                        "permissions": {
                            "$ref": "#/$defs/permissions"
                        }
                    }
                }
            },
            "additionalProperties": false
        }
    },
    "type": "object",
    "additionalProperties": true,
    "properties": {
        "groups": {
            "type": "array",
            "minContains": 0,
            "items": {
                "type": "string",
                "pattern": "[-A-Za-z0-9]+"
            }
        },
        "jenkins": {
            "type": "object",
            "additionalProperties": true
        },
        "sonar": {
            "type": "object",
            "additionalProperties": true
        },
        "nexus": {
            "type": "object",
            "additionalProperties": true
        },
        "gitlab": {
            "type": "object",
            "additionalProperties": true
        },
        "argocd": {
            "type": "object",
            "additionalProperties": true
        },
        "alfresco": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "sites": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": false,
                        "required": ["roles", "id"],
                        "properties": {
                            "id": {
                                "type": "string",
                                "pattern": "[-A-Za-z0-9]+"
                            },
                            "title": {
                                "type": "string",
                                "pattern": "[-A-Za-z0-9.]+"
                            },
                            "description": {
                                "type": "string"
                            },
                            "roles": {
                                "type": "object",
                                "minProperties": 1,
                                "additionalProperties": false,
                                "propertyNames": {
                                    "pattern": "^[-A-Za-z0-9]+$"
                                },
                                "patternProperties": {
                                    "^.*$": {
                                        "type": "object",
                                        "propertyNames": {
                                            "permissions": {
                                                "enum": [
                                                    "SiteManager",
                                                    "SiteCollaborator",
                                                    "SiteConsumer"
                                                ]
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

=== ligoj/cli/docs/bootstrap/create-roles.monprojet-sansArgo.conf.json
{
    "groups": [
        "dev",
        "admin",
        "test"
    ],
    "jenkins": {
        "folders": [
            {
                "name": "MonProjet",
                "description": "Description de MonProjet",
                "credentials": [
                    {
                        "id": "gitlab_picpipelines_grouptoken",
                        "description": "Token",
                        "stapler-class": "com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl",
                        "attributes": {
                            "$redact": "password",
                            "username": "gitlab_picpipelines_grouptoken",
                            "password": "glpat-RbLX33Yxjh3CafpPM6G6",
                            "usernameSecret": false
                        }
                    }
                ],
                "roles": {
                    "admin": {
                        "permissions": [
                            "com.cloudbees.plugins.credentials.CredentialsProvider.Create",
                            "com.cloudbees.plugins.credentials.CredentialsProvider.Delete",
                            "com.cloudbees.plugins.credentials.CredentialsProvider.ManageDomains",
                            "com.cloudbees.plugins.credentials.CredentialsProvider.Update",
                            "com.cloudbees.plugins.credentials.CredentialsProvider.View",
                            "hudson.model.Item.Build",
                            "hudson.model.Item.Cancel",
                            "hudson.model.Item.Configure",
                            "hudson.model.Item.Create",
                            "hudson.model.Item.Delete",
                            "hudson.model.Item.Discover",
                            "hudson.model.Item.Move",
                            "hudson.model.Item.Read",
                            "hudson.model.Item.Workspace",
                            "hudson.model.Run.Delete",
                            "hudson.model.Run.Update",
                            "hudson.model.View.Configure",
                            "hudson.model.View.Create",
                            "hudson.model.View.Delete",
                            "hudson.model.View.Read",
                            "hudson.scm.SCM.Tag"
                        ],
                        "recursive": false
                    },
                    "dev": {
                        "permissions": [
                            "com.cloudbees.plugins.credentials.CredentialsProvider.Create",
                            "com.cloudbees.plugins.credentials.CredentialsProvider.Delete",
                            "com.cloudbees.plugins.credentials.CredentialsProvider.ManageDomains",
                            "com.cloudbees.plugins.credentials.CredentialsProvider.Update",
                            "com.cloudbees.plugins.credentials.CredentialsProvider.View",
                            "hudson.model.Item.Build",
                            "hudson.model.Item.Cancel",
                            "hudson.model.Item.Configure",
                            "hudson.model.Item.Create",
                            "hudson.model.Item.Delete",
                            "hudson.model.Item.Discover",
                            "hudson.model.Item.Move",
                            "hudson.model.Item.Read",
                            "hudson.model.Item.Workspace",
                            "hudson.model.Run.Delete",
                            "hudson.model.Run.Update",
                            "hudson.model.View.Configure",
                            "hudson.model.View.Create",
                            "hudson.model.View.Delete",
                            "hudson.model.View.Read",
                            "hudson.scm.SCM.Tag"
                        ],
                        "recursive": false
                    },
                    "test": {
                        "permissions": [
                            "hudson.model.Item.Build",
                            "hudson.model.Item.Configure",
                            "hudson.model.Item.Discover",
                            "hudson.model.Item.Read",
                            "hudson.model.View.Read",
                            "hudson.model.Run.Replay"
                        ]
                    }
                }
            }
        ],
        "credentials": [
            {
                "id": "secret_name/Global3",
                "description": "desc",
                "stapler-class": "org.jenkinsci.plugins.plaincredentials.impl.StringCredentialsImpl",
                "scope": "SYSTEM",
                "attributes": {
                    "secret": "Global",
                    "$redact": "secret"
                }
            }
        ],

        "roles": {
            "admin": {
                "permissions": [
                    "hudson.model.Hudson.Read",
                    "hudson.model.View.Read"
                ]
            },
            "dev": {
                "permissions": [
                    "hudson.model.Hudson.Read",
                    "hudson.model.View.Read"
                ]
            },
            "test": {
                "permissions": [
                    "hudson.model.Hudson.Read",
                    "com.cloudbees.plugins.credentials.CredentialsProvider.View"
                ]
            }
        }
    },
    "nexus": {
        "repositories": [
            {
                "id": "monprojet-maven-releases",
                "format": "maven2",
                "attributes": {},
                "data": {},
                "roles": {
                    "admin": {
                        "view-permissions": [
                            "*"
                        ],
                        "admin-permissions": [
                            "*"
                        ]
                    },
                    "dev": {
                        "view-permissions": [
                            "browse",
                            "read",
                            "delete",
                            "add"
                        ],
                        "admin-permissions": [
                            "browse",
                            "read",
                            "delete"
                        ]
                    },
                    "test": {
                        "view-permissions": [
                            "browse"
                        ]
                    }
                }
            },
            {
                "id": "monprojet-maven-snapshots",
                "format": "maven2",
                "attributes": {},
                "data": {},
                "roles": {
                    "admin": {
                        "view-permissions": [
                            "*"
                        ],
                        "admin-permissions": [
                            "*"
                        ]
                    },
                    "dev": {
                        "view-permissions": [
                            "browse",
                            "read",
                            "delete",
                            "add"
                        ],
                        "admin-permissions": [
                            "browse",
                            "read",
                            "delete"
                        ]
                    },
                    "test": {
                        "view-permissions": [
                            "browse"
                        ]
                    }
                }
            }
        ]
    },
    "sonar": {
        "templates": [
            {
                "name": "sample",
                "projectPattern": "fr.gouv.finances.monprojet:*",
                "roles": {
                    "dev": {
                        "permissions": [
                            "admin"
                        ]
                    },
                    "admin": {
                        "permissions": [
                            "admin"
                        ]
                    },
                    "test": {
                        "permissions": [
                            "gateadmin",
                            "scan"
                        ]
                    }
                }
            }
        ],
        "projects": [
            {
                "name": "module1",
                "key": "module1:jar",
                "visibility": "public",
                "roles": {
                    "dev": {
                        "permissions": [
                            "admin"
                        ]
                    },
                    "admin": {
                        "permissions": [
                            "admin"
                        ]
                    },
                    "test": {
                        "permissions": [
                            "gateadmin",
                            "scan"
                        ]
                    }
                }
            }
        ],
        "roles": {
            "admin": {
                "permissions": [
                    "admin"
                ]
            }
        }
    },
    "gitlab": {
        "roles": {
            "dev": {
                "name": "Développeurs",
                "permissions": [
                    "developer"
                ]
            },
            "admin": {
                "permissions": [
                    "owner"
                ]
            },
            "test": {
                "permissions": [
                    "reporter"
                ]
            }
        }
    }
}
